sudo: true
language: node_js
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
  - node_modules
notifications:
  email: false
node_js:
  - 8
env:
  - TASK=lint
  - TASK=coverage
before_script:
  - npm prune
script: "npm run $TASK"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls