sudo: true
language: node_js
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
  - node_modules
notifications:
  email: false
node_js:
  - 8
env:
  - TASK=lint
  - TASK=travis_wait 60 npm run coverage
before_install:
- npm install -g npm codecov greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:  
- "npm run $TASK"
- codecov
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls